### ISSUE TITLE
How to use onnx_profile?

### ISSUE THREAD

**Issue by HKLee2040** [zhijian-liu/onnx-profiler#2]
If I profile onnx model with following method:
  onnx_profile(model, inputs, profiler=ActivationProfile, verbose=True)
I got error message, ActivationProfile is undefine.

If I remove "profiler=ActivationProfile", it crashs at parse_variables, i.e., line 47 of model.py

Could you help me to solve it?

**Comment by zhijian-liu** [comment]
Hi, it should be a typo, and I just fixed it. Btw, you can also try "https://github.com/mit-han-lab/torchprofile" if you are using PyTorch.
